- id: kvm_install
  type: puppet
  version: 2.1.0
  role: [compute]
  requires: [pre_deployment_start]
  required_for: [pre_deployment_end]
  condition:
    yaql_exp: &kvm changed($.get('fuel-plugin-kvm'))
  parameters:
    puppet_manifest: puppet/manifests/kvm-install.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 300

- id: kvm_node_reboot
  type: reboot
  version: 2.1.0
  role: [compute]
  requires: [kvm_install]
  required_for: [pre_deployment_end]
  condition:
    yaql_exp: *kvm
  parameters:
    timeout: 900
